---

#adds sysadmin users
- name: -> add_group
  group: name={{ item }} state=present
  with_items:
    - sysadmin
    - monitoring
  tags: add_group


- name: -> add_user
  user: name={{ item.name }} group={{ item.group }} state=present shell=/bin/bash
#  debug: msg="{{ item.name }} - {{ item.group  }}"
  with_flattened:
     - users.sysadmin
     - users.monitoring
  tags: add_users

# NB: although user's authorized_keys property is a list, only the first key in
# the list is currently managed.
#
# This is a temporary hack until I can get the users vars set up the way I'd
# like them (i.e. with the list of named users only defined once and then the
# list of users that should be present in group_vars/host_vars rather than the
# current arrangement with duplicated users.
- name: -> install_ssh_keys
  authorized_key:
          user={{ item.name }}
          key="{{ lookup('file', inventory_dir + '/../files/keys/' + item.authorized_keys[0] + '.pub') }}"
          state=present
  with_flattened:
     - users.sysadmin
     - users.monitoring
  tags: add_ssh_keys

- name: sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ item }}' line='%{{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items:
     - sysadmin
  tags: sudoers

# Add project devs if $project is defined
- name: -> add_project_group
  group: name={{ item }} state=present
  when: project is defined
  with_items:  devs_group
  tags: add_project_group

- name: -> add_project_users
  when:  project is defined
  user: name={{ item.name }} group={{ item.group }} state=present shell=/bin/bash
  with_items: users.devs_group
  tags: add_project_users

- name: -> install_project_ssh_keys
  when: project is defined
  authorized_key:
          user={{ item.name }}
          key="{{ lookup(inventory_dir + '/files/keys/' + item.authorized_keys[0] + '.pub') }}"
          state=present
  with_items:  users.devs_group
  tags: install_project_ssh_keys

- name: setup_project_sudoers
  when: project is defined
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ item }}' line='%${{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items: devs_group
  tags: setup_project_sudoers
