#ansible-playbook main.yml --tags="base-roles" -vvv
---
- hosts: "{{ host }}"
  gather_facts: True
  connection: ssh
  tags: base-roles
  user: okfn
  sudo: true
  vars_files: 
   - vars/users.yml
  vars:
     - arch: "{{ ansible_architecture }}"
  roles:
     - ansible-prereq
     - motd #adds ansible managed motd
     - iptables-persistent
     - ntpd #sets the timezone and installs openntpd
     - collectd
     - munin-node
     - check_mk-agent
     - nagios-client
     - cron
     - sysstat
     - update-notifier
     - users

- hosts: openspending-web
  gather_facts: False
  connection: ssh
  user: okfn
  sudo: true
  vars_files:
   - "{{ private_dir }}/p.yml"
  tags: openspending-web
  roles:
     - varnish
     - nginx
     - statsd

- hosts: s113.okserver.org
  gather_facts: False
  connection: ssh
  user: okfn
  sudo: true
  vars_files:
   - "{{ private_dir }}/p.yml"
  tags: etherpad
  roles:
     - { role: etherpad-lite, install_path: '/var/www/etherpad-lite', user: 'etherpad-lite', group: 'etherpad-lite', version: '1.2.11' }

- hosts: backup
  gather_facts: False
  connection: ssh
  tags: backup-server
  user: okfn
  sudo: true
  roles:
     - { role: rsnapshot, snapshot_root: '/home/backup/snapshots/', cmd_rsync: '/usr/bin/rsync' }

- hosts: ansible-dev
  gather_facts: True
  connection: ssh
  tags: graphite
  user: okfn
  sudo: true
  roles:
     - { role: booktype, install_path: '/var/www/mybooktype', user: 'booktype', group: 'booktype' }
     - graphite
 
- hosts: cache
  gather_facts: False
  connection: ssh
  tags: cache
  user: okfn
  sudo: true
  pre_tasks:
     - action: debug msg="cache!"
  roles:
     - squid3

- hosts: wiki
  gather_facts: False
  connection: ssh
  tags: wiki
  user: okfn
  sudo: true
  tasks:
     - action: debug msg="wiki!"

- hosts: s001.okserver.org
  gather_facts: True
  connection: ssh
  tags: monitoring
  user: okfn
  sudo: true
  vars_files: 
   - vars/users.yml
  roles:
     - nagios-server
     - check_mk-server

- hosts: mail
  gather_facts: False
  connection: ssh
  tags: mailserver
  user: okfn
  sudo: true
  tasks:
     - action: debug msg="mailserver!"

- hosts: listserv
  gather_facts: True
  connection: ssh
  tags: listserv
  sudo: true
  vars:
    - mailhost_type: leaf
    - relayhost: False
    - listserv: True
    - mail_domains:
        - lists.okfn.org
        - lists.knowledgeforge.net
        - lists.dataexpeditions.org
    - listserv_domains:
        - lists.okfn.org
        - lists.knowledgeforge.net
        - lists.dataexpeditions.org
    - listserv_host: lists.okfn.org
  roles:
     - postfix
     - mailman
