---
- hosts: all
  gather_facts: False
  connection: ssh
  user: okfn
  sudo: true
  vars_files: 
   - ~/ansible/vars/global.yml
   - ~/ansible/vars/users.yml
  roles:
     - ansible-prereq
     - munin-node
     - check_mk-agent
#     - nagios-client
     - sysstat
     - update-notifier
     - sysadmin-users
