---
- hosts: $host
  gather_facts: False
  connection: ssh
  user: okfn
  sudo: true
  vars_files: 
   - ~/ansible/vars/global.yml
   - ~/ansible/vars/users.yml
  roles:
     - munin-node
     - nagios-client
     - sysstat
     - update-notifier
     - sysadmin-users



























