### This *must* be in a separate file from the rest. In fact this is true
### whenever there is software in a container that must be configured alongside
### similar software on the host. In this case the culprit is postfix.
### This is because the same recipies might be run directly on the host, or
### in a container on the host. Ansible doesn't know how to execute commands
### in containers directly, so docker blurs the lines. Unblur them by
### keeping this configuration separate.


- hosts: rt
  gather_facts: True
  connection: ssh
  sudo: true
  vars_files:
   - "{{ private_dir }}/p.yml"
  ## Override vars that will be inherited from the host itself.
  vars:
   - docker_container: rt
   - mailhost_type: leaf
   - mailname: rt.okfn.org
   - transport: /dev/null
   - ses: False
   - relayhost: 172.17.42.1
   - postfix_etc: /data/rt/rt_postfix
   - aliases: rt/aliases
  roles:
   - rt
   - postfix
