- hosts: rt
  gather_facts: True
  connection: ssh
  sudo: true
  vars_files:
   - "{{ private_dir }}/p.yml"
  tasks:
  - name: docker postgres volumes
    command: mkdir -p /config/rt_pg /data/rt_pg/postgresql
  - name: docker postgres server
    docker: image=okfn/postgres:0.4 env="POSTGRES_DBA_PW={{postgres_dba_pw}}" volumes="/data/rt_pg:/data" ports=:5432
  - name: address of postgresql server
    action: set_fact db_host={{docker_containers[0].NetworkSettings.IPAddress}}
  - name: show db_host
    debug: msg="{{db_host}}"
