- hosts: rt
  gather_facts: True
  connection: ssh
  sudo: true
  vars_files:
   - "{{ private_dir }}/p.yml"
  vars:
   - docker_container: rt
   - mailhost_type: leaf
   - mailname: rt.okfn.org
   - transport: /dev/null
   - ses: False
   - relayhost: 172.17.42.1
   - postfix_etc: /data/rt/rt_postfix
   - aliases: rt/aliases
  roles:
#   - rt
   - postfix
