---
- hosts: s001.okserver.org
  gather_facts: False
  connection: ssh
  user: okfn
  sudo: true
  vars_files: 
   - ~/ansible/vars/global.yml
   - ~/ansible/vars/users.yml
  roles:
     - ansible-prereq
     - munin-node
     - munin-server
     - nagios-client
     - check_mk-agent
     - check_mk-server
     - sysstat
     - update-notifier
     - sysadmin-users
