---
# This playbook installs the munin-node client package
- name: -> install_munin-node
  action: apt pkg=munin-node state=latest
  tags: install_munin-node

- name: -> add_munin_user
  action: user name=munin group=munin state=present shell=/bin/false home=/var/lib/munin
  tags: add_munin_user

- name: -> add_munin_group
  action: group name=munin state=present 
  tags: add_munin_group

- name: -> install_munin-plugins-extra
  action: apt pkg=munin-plugins-extra state=latest
  tags: install_munin-plugins-extra

- name: -> setup_munin_node_config
  action: copy src=etc/munin-node.conf dest=/etc/munin/munin-node.conf force=yes
  notify: restart munin-node
  tags: setup_munin_config

- name: -> setup_munin_node_cron
  action: copy src=etc/cron.d/munin-node dest=/etc/cron.d/munin-node force=yes
  tags: setup_munin_config
