---
# This playbook installs the munin-node client package
- name: -> install_munin-node
  action: apt pkg=munin-node state=latest
  tags: install_munin-node

- name: -> add_munin_user
  action: user name=munin group=munin state=present shell=/bin/false home=/var/lib/munin
  tags: add_munin_user

- name: -> add_munin_group
  action: group name=munin state=present 
  tags: add_munin_group

- name: -> install_munin-plugins-extra
  action: apt pkg=munin-plugins-extra state=latest
  tags: install_munin-plugins-extra

- name: -> setup_munin_node_config
  action: copy src=etc/munin-node.conf dest=/etc/munin/munin-node.conf force=yes
  notify: restart munin-node
  tags: setup_munin_config

- name: -> setup_munin_node_cron
  action: copy src=etc/cron.d/munin-node dest=/etc/cron.d/munin-node force=yes
  tags: setup_munin_config

#check if munin is allowed in the firewall
##- name: firewall_check_rule 
#  action: shell sudo iptables-save | grep -q "dport {{ munin_port }}"
#  ignore_errors: true
#  register: rule_present
#  tags: firewall_check_rule

- name: -> allow_munin_in_fw
  action: lineinfile dest=${iptables_config_file} regexp='dport ${munin_port} -j monitoring$'  line='-A INPUT -s ${monitoring_server} -p tcp -m tcp --dport ${munin_port} -j monitoring' insertbefore='^COMMIT' state=present
  notify: restart iptables-persistent
  tags: allow_munin_in_fw


#- name: firewall_allow_munin
#  action: shell sudo iptables -A monitoring -s {{ monitoring_server }}  -p tcp -m tcp --dport 4949 -j ACCEPT 
#  when: rule_present.rc == 1
#  tags: firewall_allow_munin 
