---
docker_host: true

sites_enabled:
  - rt.okfn.org
  - sendy.okfn.org
sites_to_monitor:
  - rt.okfn.org:80:301 # SSL redirect
  - sendy.okfn.org:80:200
ssl_sites_to_monitor:
  - rt.okfn.org
  - sendy.okfn.org
nginx_ssl_certs:
  - star_okfn_org

# postfix config
mailhost_type: leaf
relayhost: False
ses: False
relay_domains: ['rt.okfn.org']
transport: "{{ inventory_hostname }}/transport"
