---
dbserver: localhost
managed: false
hoster: RS
db_type: mysql
sites_enabled:
  - product.okfn.org
  - product-open-data.com
  - wikifarm
sites_to_monitor:
  - product-open-data.com:80:200
  - product.okfn.org:80:200
  - wiki.okfn.org:80:301
enabled_plugin_checks:
  - mk_mysql
backup_scripts:
  - mysql_backup.sh
mysql_exclude_dbs:
  - test
private_ip: 10.179.249.37
users_extra:
  - name: 'harry.wood'
    groups:
      - sysadmin
    authorized_keys:
      - 'harry.wood'
