---
docker_host: true

sites_enabled:
  - rt.okfn.org
  - sendy.okfn.org
  - booktype.okfn.org
sites_to_monitor:
  - rt.okfn.org:80:301 # SSL redirect
  - sendy.okfn.org:80:301 # SSL redirect
ssl_sites_to_monitor:
  - rt.okfn.org
  - sendy.okfn.org
nginx_ssl_certs:
  - star_okfn_org

# postfix config
postfix_additional_aliases: |
  school-of-data: /dev/null
postfix_additional_trusted_networks: "172.17.0.0/16"
postfix_relay_domains:
  - rt.okfn.org
postfix_transport: |
  rt.okfn.org                   smtp:127.0.0.1:5025
  school-of-data@lists.okfn.org local:
postfix_recipient_access: |
  # Don't send emails to non-humans
  /^(noreply|no-reply|MAILER-DAEMON|nagios)@/ REJECT
postfix_sender_access: |
  tenderapp.com      REJECT
  pm.mtasv.net       REJECT
  rackspacecloud.com REJECT

database_container: rt_pg
dumper_container: dumper
dump_databases: rt4
dumper_s3_bucket: s115_pg_dump
dumper_snitch_url: "https://nosnch.in/32cc60bb75"

backup_scripts:
   - mysql_backup.sh

mysql_backup_list:
   - sendy
   - mysql

mysql_port: 49158
mysql_host: 127.0.0.1
