---
rackspace: false
nginx_ssl_certs:
  - star_okfn_org
sites_enabled:
  - lists.okfn.org
mailhost_type: leaf
postfix_managed: true
relayhost: false
ses: false
origin: okfn.org
listserv: true
mm_spamassassin: true
transport: list_transport
aliases: "{{ inventory_hostname }}/aliases"
graphite_collectors: [ 'mailman_stats.py' ]
check_graphite: ['sum(mail_metrics.mailman.subscribe.*.pending):-1hours:20:30']
check_parameters: ['Postfix Queue:80:120']
postfix_map_files: ['access','helo_access','transport']
postfix_managed: true
postfix_relay_domains:
  - lists.okfn.org
  - lists.knowledgeforge.net
  - lists.dataexpeditions.org
mailman_list_host: lists.okfn.org
mailman_additional_list_hosts:
  - lists.knowledgeforge.net
  - lists.dataexpeditions.org
  - list.irail.be
