---
hosted: aws
docker_host: true

#for nagios
sites_to_monitor: 
  - pad.okfn.org:80:301 # monitor port 80, and check for status 200
  - booktype.okfn.org:80:200
  - rt.okfn.org:80:301 # SSL redirect

ssl_sites_to_monitor:
  - rt.okfn.org
  - pad.okfn.org

#for nginx
sites_enabled:
  - rt.okfn.org
  - pad.okfn.org
  - booktype.okfn.org
  - sendy.okfn.org

nginx_ssl_certs:
  - star_okfn_org

# postfix config
postfix_additional_aliases: |
  school-of-data: /dev/null
postfix_additional_trusted_networks: "172.17.0.0/16"
postfix_relay_domains:
  - rt.okfn.org
postfix_transport: |
  rt.okfn.org                   smtp:127.0.0.1:49153
  school-of-data@lists.okfn.org local:
# We use recipient_access to enable restrictions on outbound mail from RT. Use
# DISCARD rather than reject (thus simulating successful delivery) to prevent
# RT's own postfix instance from accumulating failed deliveries in the queue.
postfix_recipient_access: |
  # Don't send emails to non-humans
  /^(noreply|no-reply|MAILER-DAEMON|nagios)@/ DISCARD
  # Don't send emails to our machines
  /^root@[^.]+\.okserver\.org/                DISCARD
postfix_sender_access: |
  tenderapp.com      REJECT
  pm.mtasv.net       REJECT
  rackspacecloud.com REJECT

#for mysql backups
db_type: mysql
mysql_host: 127.0.0.1
mysql_port: 3306
backup_scripts: ['mysql_backup.sh', 'psql_backup.sh']
mysql_backup_list: 
  - mysql
  - etherpad-lite

#enabled_plugin_checks: ['mk_mysql'] #mk_mysql adopted from http://mathias-kettner.de/checkmk_mysql.html

#for psql backups
psql_host: db001.cxglaymtrf0h.eu-west-1.rds.amazonaws.com
psql_backup_list:
  - rt4
  - booktype

#RT docker instance config
rt_db_user: rt_user
rt_db_name: rt4
rt_name: rt.okfn.org
rt_org: OKF
rt_web_port: 443
rt_web_domain: rt.okfn.org

users_extra:
  - name: 'vitor'
    groups:
      - docker
      - sysadmin
    authorized_keys:
      - 'vitor'
