---
- name: install_varnish
  apt: pkg={{ item }} state=installed
  with_items:
     - varnish
     - libvarnishapi1
  tags:
     - install_varnish
     - varnish

- name: add_config_varnish
  copy: src={{ inventory_hostname }}/default.vcl dest=/etc/varnish/default.vcl
  notify: restart varnish
  tags:
     - add_config_varnish
     - varnish

- name: add_config_default_varnish
  copy: src={{ inventory_hostname }}/varnish dest=/etc/default/varnish
  notify: restart varnish
  tags:
     - add_config_default_varnish
     - varnish

- name: secrets_varnish
  template: src=secret.j2 dest=/etc/varnish/secret
  tags:
     - secrets_varnish
     - varnish
