---
- name: reload postfix
  service: name=postfix state=reloaded

- name: postalias aliases
  shell: postalias hash:/etc/postfix/aliases

- name: postmap access
  shell: postmap hash:/etc/postfix/access

- name: postmap sender_access
  shell: postmap hash:/etc/postfix/sender_access

- name: postmap recipient_access
  shell: postmap hash:/etc/postfix/recipient_access

- name: postmap transport
  shell: postmap hash:/etc/postfix/transport
