---
- hosts: $host
  user: okfn
  gather_facts: False
  vars_files:
   - ~/ansible/vars/global.yml 
   - ~/ansible/vars/users.yml
  tasks:
  
     - name: -> add_group
       action: group name=${item.group} state=present
       with_items:
         - ${users.ckan-dev}
 
     - name: -> add_user
       action: user name=${item.name} group=${item.group} state=present shell=/bin/bash
       with_items: 
         - ${users.ckan-dev}  

     - name: -> install_ssh_keys"
       action: authorized_key user=${item.name} state=present key=${item.pub_key}
       with_items: 
          - ${users.ckan-dev}
