- name: install_postfix 
  action: apt pkg=postfix state=present 
  notify: restart postfix 
  tags: 
     - install_postfix
     - postfix

- name: setup_leaf_main_cf
  template: src={{ mailhost_type }}.cf dest=/etc/postfix/main.cf
  notify: restart postfix

- name: default_aliases
  template: src=aliases dest=/etc/postfix/aliases owner=postfix group=postfix mode=0644

- name: fixup_postfix_perms
  action: shell chgrp postfix /etc/postfix && chmod 1775 /etc/postfix

- name: fixup_alias_link
  action: shell rm -f /etc/aliases && ln -s /etc/postfix/aliases /etc

- name: cleanup_alias_db_link
  action: shell rm -f /etc/aliases.db

- name: newaliases
  action: shell newaliases

- name: create_transport_maps
  when: listserv == True
  template: src=list_transport dest=/etc/postfix/transport owner=postfix group=postfix mode=0644

- name: build_transport_maps
  when: listserv == True
  command: postmap /etc/postfix/transport

- name: create_sasl_password
  when: ses == True
  template: src=sasl_passwd dest=/etc/postfix/sasl_passwd owner=postfix group=postfix mode=0600

- name: build_sasl_passwd
  when: ses == True
  command: postmap /etc/postfix/sasl_passwd

