#depends on timezone = being defined under inventory/host_vars or inventory/group_vars
---

- name: check_timezone
  shell: diff -s /etc/localtime /usr/share/zoneinfo/{{ timezone }}
  register: timezone_ok
  ignore_errors: true
  tags:
     - check_timezone
     - ntpd

- name: check_timezone_file_exists
  shell: test -f /etc/timezone
  register: timezonefile_exists
  ignore_errors: True
  tags:
     - check_timezone_file_exists
     - ntpd

- name: setup_timezone
  shell: echo {{ timezone }} > /etc/timezone
  when: timezone_ok.rc != 0 or timezonefile_exists != 0
  tags:
     - setup_timezone
     - ntpd

- name: reconfigure_to_new_timezone
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: timezone is defined and timezone_ok.rc != 0
  tags:
     - reconfigure_to_new_timezone
     - ntpd

#https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061 workaround
- name: purge_ntpd
  apt: pkg=ntp state=absent purge=yes
  ignore_errors: True
  notify: restart openntpd
  register: ntpd_purged
  tags:
     - purge_ntpd
     - ntpd

- name: restart_AA #reload apparmor to re-read profile
  shell: service apparmor restart
  when: ntpd_purged|success
  ignore_errors: True
  tags:
     - ntpd
     - restart_apparmor

- name: check_if_ntpd_has_apparmour_profile #in some cases ntpd has been overwritten, we move the apparmor file
  shell: test -f /etc/apparmor.d/usr.sbin.ntpd
  register: AA_profile_present
  ignore_errors: True
  tags:
     - check_if_ntpd_has_apparmour_profile
     - ntpd

- name: disable_ntpd_AA_profile
  shell: mv /etc/apparmor.d/usr.sbin.ntpd /etc/apparmor.d/disable/ && service apparmor restart
  when: AA_profile_present|success
  ignore_errors: True
  tags:
     - ntpd

- name: install_openntpd
  apt: pkg=openntpd state=present
  notify: restart openntpd
  tags:
     - install_openntpd
     - ntpd

- name: reload cron #this is required or else cron doesnt pickup on the new timezone
  shell: service cron reload
  ignore_errors: True
  tags:
     - reload_cron
     - ntpd
     - setup_timezone
