---
- include_vars: "{{ private_dir }}/p.yml"

- name: add nagios user
  user: name=nagios state=present

- name: install nagios3
  apt: pkg='{{ item }}' state=present
  with_items:
    - nagios3
    - fcgiwrap
  notify: setuid nagios plugins

- name: setup symlinks for nagios cgi
  file: src='{{ item.src }}' dest='{{ item.dest }}' state=link
  with_items:
    - src: /etc/nagios3/stylesheets
      dest: /usr/share/nagios3/htdocs/stylesheets
    - src: /usr/share/nagios3/htdocs/
      dest: /usr/share/nagios3/htdocs/nagios3

- name: add private key for check_by_ssh checks
  copy: src='{{ private_dir }}/nagios_id_rsa.private'
        dest=/home/nagios/.ssh/id_rsa
        owner=nagios
        group=monitoring
        mode=600

- name: setup ssh config to disable strict host checking
  copy: src=ssh_config
        dest=/home/nagios/.ssh/config
        owner=nagios
        group=monitoring
        mode=600

- name: nagios_config
  copy: src='{{ item }}' dest=/etc/nagios3/
  notify: reload nagios
  with_fileglob:
    - etc/nagios3/*

- name: nagios_config_confd
  copy: src='{{ item }}' dest=/etc/nagios3/conf.d/
  notify: reload nagios
  with_fileglob:
    - etc/nagios3/conf.d/*

- name: install deps for pagerduty plugin
  apt: pkg='{{ item }}' state=present
  with_items:
  - libwww-perl
  - libcrypt-ssleay-perl

- name: install custom nagios plugins
  copy: src='usr/local/bin/{{ item }}'
        dest='/usr/local/bin/{{ item }}'
        mode=755
        owner=nagios
  notify: reload nagios
  with_items:
    - check_graphite.py
    - pagerduty_nagios.pl

- name: install pagerduty config
  template: src=etc/nagios3/conf.d/pagerduty_nagios.cfg.j2
            dest=/etc/nagios3/conf.d/pagerduty_nagios.cfg
            owner=nagios
  notify: reload nagios

- name: install pagerduty cronjob
  copy: src=etc/cron.d/pagerduty_nagios
        dest=/etc/cron.d/pagerduty_nagios
        mode=755
        owner=root
        group=root

