#Todo add handlers to reload carbon_cache.py
- name: easy_install_pip
  easy_install: name=pip
  tags: easy_install_pip

- name: pip_install_carbon # pip can move into its own role
  pip: name={{ item }}
  with_items:
     - carbon
     - whisper
     - graphite-web
#     - pycairo   - can't seem to install this on py 2.x, going with the apt pkg
     - Django
     - django-tagging
     - python-memcached
  tags: pip_install_carbon

- name: add_graphite_user
  user: name=graphite home=/opt/graphite/
  tags: add_graphite_user

- name: add_graphite_config
  copy: src={{ item }} dest=/opt/graphite/conf/
  with_fileglob:
     - opt/graphite/conf/*

- name: add_graphite_webapp_config
  copy: src={{ item }} dest=/opt/graphite/webapp/
  with_items:
     - opt/graphite/webapp/graphite/local_settings.py
     - opt/graphite/webapp/graphite/graphite_uwsgi.py

- name: ensure_graphite_perms
  file: path=/opt/graphite/ state=directory owner=graphite group=graphite
  tags: ensure_graphite_perms

