- name: setup community_admin script
  copy: src=community_admin.py
        dest=/usr/lib/mailman/bin/community_admin.py
        owner=root
        group=root
        mode=644
  tags:
     - community_admin

- name: community_admin config
  template: src=community_admin.conf.j2
            dest=/etc/mailman/community_admin.conf
            owner=root
            group=root
            mode=644
  tags:
     - community_admin

- name: community lists list
  copy: src=community_lists
        dest=/etc/mailman/community_lists
        owner=root
        group=root
        mode=644
  notify: update community_admin
  tags:
     - community_admin

