- name: install_mailman
  apt: pkg=mailman state=present
  notify: restart mailman

- name: configure_mailman
  template: src=mm_cfg.py dest=/etc/mailman/mm_cfg.py owner=root group=root mode=0644
  notify: restart mailman
  tags: mailman_config

- name: install_fcgiwrap
  apt: pkg=fcgiwrap state=present

- name: install nginx mailman_fcgi config
  copy: src=mailman_fcgi
        dest=/etc/nginx/mailman_fcgi
        owner=root
        group=root
        mode=644
  notify: reload nginx

- name: install change_mod_pw script
  copy: src=change_mod_pw
        dest=/usr/lib/mailman/bin
        owner=root
        group=list
        mode=755

- include: patches.yml
