- name: install_mailman
  apt: pkg=mailman state=present
  notify: restart mailman

- name: configure_mailman
  template: src=mm_cfg.py dest=/etc/mailman/mm_cfg.py owner=root group=root mode=0644
  notify: restart mailman

- name: install_fcgiwrap
  apt: pkg=fcgiwrap state=present

- name: install nginx mailman_fcgi config
  copy:
          src=mailman_fcgi
          dest=/etc/nginx/mailman_fcgi
          owner=root
          group=root
          mode=644
  notify: reload nginx


- name: setup community_admin script
  copy:
          src=community_admin.py
          dest=/usr/lib/mailman/bin/community_admin.py
          owner=root
          group=root
          mode=644
  tags:
     - community_admin

- name: community_admin config
  template:
          src=community_admin.conf.j2
          dest=/etc/mailman/community_admin.conf
          owner=root
          group=root
          mode=644
  tags:
     - community_admin

- name: community lists list
  copy:
          src=community_lists
          dest=/etc/mailman/community_lists
          owner=root
          group=root
          mode=644
  notify: update community_admin
  tags:
     - community_admin
