---
 - name: check if omeka is installed
   stat: path=/var/www/omeka/.installed
   register: omeka_exists

 - name: Get the omeka source code
   get_url: url=http://omeka.org/files/omeka-2.2.2.zip dest=/tmp
   when: omeka_exists.stat.exists == false

 - name: Unzip the source code
   unarchive: src=/tmp/omeka-2.2.2.zip dest=/tmp copy=no creates=no
   when: omeka_exists.stat.exists == false

 - name: Create /var/www
   file: path=/var/www state=directory
   when: omeka_exists.stat.exists == false

 - name: Move omeka code into /var/www/omeka
   command: mv /tmp/omeka-2.2.2/ /var/www/omeka/
   when: omeka_exists.stat.exists == false

 - name: Copy config file over to Omeka
   template: src=db.ini.j2 dest=/var/www/omeka/db.ini owner=www-data group=www-data mode=0644
   when: omeka_exists.stat.exists == false

# The database is already setup in RDS, so no work needs to be done on the DB.

 - name: Download all the plugins
   get_url: url={{ item.url }} dest=/tmp
   with_items:
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Guest-User-1.1.1.zip', name: 'guest-user' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Geolocation-2.2.3.zip', name: 'geolocation' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Embed-Codes-1.0.zip', name: 'embed-codes' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Contribution-3.0.1.zip', name: 'contribution' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Derivative-Images-2.0.zip', name: 'derivative-images' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Commenting-2.1.2.zip', name: 'commenting' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/CSV-Import-2.0.3.zip', name: 'csv-import' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Digital-Object-Linker-Plugin-1.0.zip', name: 'digital-object-linker' }
     - { url : 'http://omeka.org/wordpress/wp-content/uploads/Search-By-Metadata-1.2.zip', name: 'search-by-metadata' }
   when: omeka_exists.stat.exists == false

 - name: Extract all the plugins into plugin directory
   unarchive: src=/tmp/{{ item }} dest=/var/www/omeka/plugins/ copy=no
   with_items:
     - Guest-User-1.1.1.zip
     - Geolocation-2.2.3.zip
     - Embed-Codes-1.0.zip
     - Contribution-3.0.1.zip
     - Derivative-Images-2.0.zip
     - Commenting-2.1.2.zip
     - CSV-Import-2.0.3.zip
     - Digital-Object-Linker-Plugin-1.0.zip
     - Search-By-Metadata-1.2.zip
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka directory
   file: path=/var/www/omeka/files owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka directory
   file: path=/var/www/omeka/admin owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka directory
   file: path=/var/www/omeka/plugins owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka directory
   file: path=/var/www/omeka/application owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Create installed file in /var/www/omeka
   file: path=/var/www/omeka/.installed owner=www-data group=www-data mode=0644 state=touch
   when: omeka_exists.stat.exists == false
