---
# This playbook installs the iptables-persistant package
- name: install_iptables_persistent
  environment:
     DEBIAN_FRONTEND: noninteractive
  apt: pkg=iptables-persistent state=present
  notify: restart iptables-persistent 
  tags: install_iptables_persistent

- name: iptables_config
  template: src=etc/iptables/iptables.j2 dest=/etc/iptables/rules.v4
  notify: restart iptables-persistent
  tags: iptables_config


