---
- name: copy config into apt.conf.d folder
  templates: src=20mainubuntumirrors.j2 dest=/etc/apt/sources.list.d/mainubuntumirrors.list
  when: ansible_distribution == 'Ubuntu'
  tags: copy_apt_config
