---
#adds sysadmin users
- name: -> add_group
  action: group name={{ item }} state=present
  with_items:
    - sysadmin
    - monitoring
  tags: add_group


- name: -> add_user
  action: user name={{ item.name }} group={{ item.group }} state=present shell=/bin/bash
#  action: debug msg="{{ item.name }} - {{ item.group  }}"
  with_flattened: 
     - users.sysadmin
     - users.monitoring
  tags: add_users

- name: -> install_ssh_keys
#  action: debug msg="{{ item.name }} - {{ item.key  }}"
  action: authorized_key user={{ item.name }} state=present key="{{ item.key }}" 
  with_flattened:
     - users.sysadmin
     - users.monitoring
  tags: add_ssh_keys

- name: sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ item }}' line='%{{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items:
     - sysadmin
  tags: sudoers

# Add project devs if $project is defined
- name: -> add_project_group
  action: group name={{ item }} state=present
  when: project is defined
  with_items:  devs_group
  tags: add_project_group

- name: -> debug_set
#  action: debug msg="{{ project }} {{ devs_group }}"
  action: debug msg="--> {{ item.name }}"
  with_items: users.devs_group
  tags: debug_set

- name: -> add_project_users
  when:  project is defined
  action: user name={{ item.name }} group={{ item.group }} state=present shell=/bin/bash
  with_items: users.devs_group
  tags: add_project_users

- name: -> install_project_ssh_keys
  when: project is defined
  action: authorized_key user={{ item.name }} state=present key="{{ item.key }}"
  with_items:  users.devs_group
  tags: install_project_ssh_keys

- name: setup_project_sudoers
  when: project is defined
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ item }}' line='%${{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items: devs_group
  tags: setup_project_sudoers
