- name: install python
  apt: pkg=python state=installed

- name: install python 3
  apt: pkg=python3 state=installed
  when: install_python3

- name: install core python packages
  apt: pkg='{{ item }}' state=installed
  with_items:
    - python-setuptools
    - python-virtualenv
