---
# This play sets up the check_mk server

- name: install check-mk_server
  action: apt pkg=check-mk-server state=installed
  tags: 
     - install_check-mk_server
     - check-mk_server

- name: check_mk_config_main
  action: template src=etc/check_mk/main.mk.j2 dest=/etc/check_mk/main.mk
  notify: reload check_mk
  tags: 
     - check_mk_config_main
     - check-mk_server

- name: check_mk_config_multisite
  action: copy src=etc/check_mk/multisite.mk dest=/etc/check_mk/multisite.mk force=yes
  tags:  
     - check_mk_config_multisite
     - check-mk_server

- name: manual_reload_check_mk_server
  action: shell /usr/bin/check_mk -II && /usr/bin/check_mk -O
  tags: 
     - manual_reload_check_mk_server
     - check-mk_server
