---
- name: check_and_reload_sshd
  command: "{{ sshd_binary }} -t"
  notify: reload_sshd

- name: reload_sshd
  service:
    name: "{{ sshd_service }}"
    state: reloaded
  when: sshd_allow_reload == True
