---
- name: install postgrey
  apt: pkg=postgrey state=installed

- name: setup postgrey default
  copy: src={{ item }} dest=/{{ item }}
  with_items:
     - etc/default/postgrey
     - etc/postgrey/whitelist_clients 
  notify: reload postgrey
