---
# This playbook installs the munin-node client package
- name: -> install_munin-node
  action: apt pkg=munin-node ensure=installed
  tags: install_munin-node

- name: -> install_munin-plugin-extras
  action: apt pkg=munin-plugin-extras ensure=installed
  tags: install_munin-plugin-extras

- name: -> setup_munin_node_config
  action: copy src=$item dest=/etc/munin/ state=present
  with_fileglob:
     - files/munin-node/munin/*
  action: copy src=$item dest=/etc/munin/ state=present
  with_fileglob:
     - files/munin-node/munin/*
  action: copy src=$item dest=/etc/munin/plugin-conf.d/ state=present
  with_fileglob:
     - files/munin-node/munin/plugin-conf.d/*
  action: copy src=$item dest=/etc/munin/templates/ state=present
  with_fileglob:
     - files/munin-node/munin/templates/*
  tags: setup_munin_config
