---
#This playbook installs packages and copies over the appropriate config file

- name: -> install_pkg
  action: apt pkg=$item state=present

  with_items: $pkg_list
  tags: install_pkg

#- name: -> setup config
#  action: copy 
#- name: -> install_ssh_keys
#  action: authorized_key user=$item state=present key='$FILE(files/users/ssh_keys/${item}.pub)'
#  with_items: $user_list
#  tags: install_ssh_keys
