#meta/main.yml installs the rsnapshot package.
---
- name: create_backup_directory
  action: file path={{ snapshot_root }} owner=root group=root state=directory
  tags: create_backup_directory 

- name: rsnapshot_config
  action: template src=etc/rsnapshot.conf.j2 dest=/etc/rsnapshot.conf
