#installs booktype from the custom deb - with a bunch of fixes to path and env .
---
- name: add_booktype_group
  user: name={{ group }} state=present
  tags: add_booktype_group

- name: add_booktype_user
  user: name={{ user }} group={{ group }} home={{ install_path }}
  tags: add_booktype_user

- name: fetch_booktype_deb
  get_url: url=http://apt.okserver.org/all/mybooktype-1.6-okf-custom_1.0_all.deb dest=/opt/mybooktype-1.6-okf-custom_1.0_all.deb force=yes
  tags: fetch_booktype_deb

- name: install_booktype_deb
  shell: dpkg -i /opt/mybooktype-1.6-okf-custom_1.0_all.deb creates={{ install_path }}/mybook
  tags: install_booktype_deb

- name: set_permissions_booktype
  file: path={{ install_path }} owner={{ user }} group={{ group }} recurse=yes state=directory
  tags: set_permissions_booktype
