---
# This playbook deploys nagios plugins for monitoring purposes.
- name: -> install_nagios_plugins
  action: apt pkg=nagios-plugins state=installed
  tags: install_nagios_plugins

- name: -> add_monitoring_group
  action: group name=${item} state=present
  with_items:
    - monitoring
  tags: add_group

- name: -> add_user
  action: user name=${item.name} group=${item.group} state=present shell=/bin/bash
  with_items: 
    - ${users.monitoring}
  tags: add_users
