# ansible-playbook main.yml -vvv --tags="fetch_collectd_deb,install_collectd_deb,collectd_init_script,setup_collectd_config" --extra-vars="host=all"
---
- name: fetch_collectd_deb
#  shell: wget http://apt.okserver.org/{{ ansible_architecture }}/collectd-okfcustom-5.4.0_1.0_{{ ansible_architecture }}.deb -O /opt/collectd-okfcustom-5.4.0_1.0_{{ ansible_architecture }}.deb creates=/opt/collectd-okfcustom-5.4.0_1.0_{{ ansible_architecture }}.deb
  get_url: url=http://apt.okserver.org/{{ ansible_architecture }}/collectd-okfcustom-5.4.0_1.0_{{ ansible_architecture }}.deb dest=/opt/collectd-okfcustom-5.4.0_1.0_{{ ansible_architecture }}.deb force=yes
  tags:
     - fetch_collectd_deb
     - collectd

- name: install_collectd_deb
  shell: dpkg -i /opt/collectd-okfcustom-5.4.0_1.0_{{ ansible_architecture }}.deb creates=/opt/collectd/etc/collectd.conf
  tags:
     - install_collectd_deb
     - collectd


- name: setup_collectd_config
  template: src={{ item }} dest=/opt/collectd/etc/collectd.conf
  with_first_found:
     - files:
          - opt/collectd/etc/{{ inventory_hostname }}/collectd.conf.j2
          - opt/collectd/etc/{{ project }}/collectd.conf.j2
          - opt/collectd/etc/collectd.conf.j2
       paths:
          - ../templates
  tags:
     - setup_collectd_config
     - collectd

- name: collectd_init_script
  copy: src=opt/collectd/etc/init.d/collectd dest=/etc/init.d/collectd
  tags:
     - collectd_init_script
     - collectd

- name: reload_collectd
  shell: service collectd restart
  when: reload_collectd is defined #pass true with --extra-vars="reload_collectd=True"
  tags:
     - reload_collectd
     - collectd
