---
# This playbook installs munin
- name: -> install_munin_server
  action: apt pkg=munin state=installed
  tags: install_munin_server

- name: -> setup_munin_config
  action: copy src=$item dest=/etc/munin/
  with_fileglob:
     - files/munin-server/munin/*
  action: copy src=$item dest=/etc/munin/
  with_fileglob:
     - files/munin-server/munin/*
  action: copy src=$item dest=/etc/munin/plugin-conf.d/*
  with_fileglob:
     - files/munin-server/munin/plugin-conf.d/*
  action: copy src=$item dest=/etc/munin/templates/*
  with_fileglob:
     - files/munin-server/munin/templates/*
  tags: setup_munin_config
