---
#This playbook deploys users and thier ssh keys

- name: -> add_user
  action: user name=$item comment="Monitoring" state=present shell=/bin/bash
  with_items: $user_list
  tags: add_user

- name: -> install_ssh_keys
  action: authorized_key user=$item state=present key='$FILE(files/users/ssh_keys/${item}.pub)'
  with_items: $user_list
  tags: install_ssh_keys
