---
- name: nagios_config
  action: copy src={{ item }} dest=/etc/nagios3/
  notify: reload nagios
  with_fileglob: 
     - etc/nagios3/*
  tags: 
     - nagios_config
     - nagios

- name: nagios_config_confd
  action: copy src={{ item }} dest=/etc/nagios3/conf.d/
  notify: reload nagios
  with_fileglob:
     - etc/nagios3/conf.d/*
  tags: 
     - nagios_config_confd
     - nagios

- name: nagios_config
  action: copy src=usr/local/bin/pagerduty_nagios.pl dest=/usr/local/bin/pagerduty_nagios.pl mode=755 owner=nagios
  notify: reload nagios
  with_fileglob: 
     - etc/nagios3/*
  tags: 
     - nagios
     - nagios_pagerduty
     - nagios_pagerduty_script

- name: nagios_pagerduty_config
  action: template src=etc/nagios3/conf.d/pagerduty_nagios.cfg.j2 dest=/etc/nagios3/conf.d/pagerduty_nagios.cfg owner=nagios
  notify: reload nagios
  tags: 
    - nagios
    - nagios_pagerduty
    - nagios_pagerduty_config

- name: nagios_pagerduty_cron
  action: copy src=etc/cron.d/pagerduty_nagios dest=/etc/cron.d/pagerduty_nagios mode=755 owner=root group=root
  tags: 
    - nagios
    - nagios_pagerduty
    - nagios_pagerduty_cron


