---
- name: fetch_statsd_deb
  get_url: url=http://apt.okserver.org/x86_64/statsd_0.6.0-ppa2~precise_amd64.deb dest=/opt/statsd_0.6.0-ppa2~precise_amd64.deb force=yes
  tags:
     - fetch_statsd_deb
     - statsd

- name: install_statsd_deb
  shell: dpkg -i /opt/statsd_0.6.0-ppa2~precise_amd64.deb creates=/etc/statsd.conf
  tags:
     - install_statsd_deb
     - statsd
- name: setup statsd_config
  template: src={{ item }} dest=/etc/statsd.conf
  with_first_found:
     - files:
          - etc/statsd.conf.j2
          - etc/{{ project }}/statsd.conf.j2
          - etc/{{ inventory_hostname }}/statsd.conf.j2
       paths:
          - ../templates
  notify: restart statsd
  tags:
     - setup_statsd_config
     - statsd
