---
#adds sysadmin users
- name: -> add_group
  action: group name=${item} state=present
  with_items:
    - sysadmin
    - monitoring
  tags: add_group

- name: -> add_user
  action: user name=${item.name} group=${item.group} state=present shell=/bin/bash
  with_items:
    - ${users.sysadmin}
    - ${users.monitoring}
  tags: add_users

- name: -> install_ssh_keys
  action: authorized_key user=${item.name} state=present key="${item.key}" # key='$FILE(~/ansible/files/users/ssh/${item.name}.pub)'
  with_items:
     - ${users.sysadmin}
     - ${users.monitoring}
  tags: add_ssh_keys

- name: sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%${item}' line='%${item} ALL=(ALL) NOPASSWD: ALL'"
  with_items:
     - sysadmin
  tags: sudoers

## Add project devs if $project is defined
#- name: -> add_project_group
#  when_set: {{ project }}
#  action: group name=${item} state=present
#  with_items:
#    - ${devs_group}
#  tags: add_project_group
#
#- name: -> debug_set
#  when_set: {{ project }}
#  action: debug msg=project is {{ project }}
#  tags: debug_set
#
#- name: -> add_project_users
#  when_set: {{ project }}
#  action: user name={{ item.name }} group={{ item.group }} state=present shell=/bin/bash
#  with_items: users.{{ devs_group }}
#  tags: add_project_users
#
#- name: -> install_project_ssh_keys
#  when_set: {{ project }}
#  action: authorized_key user=${item.name} state=present key="${item.key}"
#  with_items: users.{{ devs_group }}
#  tags: install_project_ssh_keys
#
#- name: setup_project_sudoers
#  when_set: {{ project }}
#  lineinfile: "dest=/etc/sudoers state=present regexp='^%${item}' line='%${item} ALL=(ALL) NOPASSWD: ALL'"
#  with_items:
#     - ${devs_group}
#  tags: setup_project_sudoers
#
