---
#variables that you'd like to apply to all ckan servers
project: 'ckan'
devs_group: 'ckan_dev'
postgres_port: 5432
solr_port: 8983
db_type: postgres
sysadmin_email: "{{ ckan_sysadmin_email }}"
ckan_locale_default: en
