---
- hosts: all
  gather_facts: False
  connection: ssh
  user: okfn
  vars_files: 
   - ~/ansible/vars/global.yml
   - ~/ansible/vars/users.yml
  tasks:
     - name:  add_admin_groups
       action: group name=${item} state=present
       with_items:
         - sysadmin
         - monitoring
    
     - name: add_admin_users
       action: user name=${item.name} group=${item.group} state=present shell=/bin/bash
       with_items: 
         - ${users.sysadmin}
         - ${users.monitoring}

     - name: install_admin_ssh_keys
       action: authorized_key user=${item.name} state=present key="${item.key}" # key='$FILE(~/ansible/files/users/ssh/${item.name}.pub)'
       with_items: 
          - ${users.sysadmin}
          - ${users.monitoring}
       tags: add_ssh_keys

     - name: sudoers
       lineinfile: "dest=/etc/sudoers state=present regexp='^%${item}' line='%${item} ALL=(ALL) NOPASSWD: ALL'"
       with_items:
          - sysadmin
       tags: sudoers

     - name: ensure_important_packages
       action: apt state=installed pkg=${item}
       with_items:
          - update-notifier-common
          - nagios-plugins

     - name: ensure_all_packages_updated
       action: apt upgrade=yes
